mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('tfe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/tfe/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import TabList, TabDetail, TabCreate, TabUpdate, TabDelete, CustomLoginView, RegisterPageView

app_name = 'tfe'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='tfe:login'), name='logout'),
    path('register/', RegisterPageView.as_view(), name='register'),
    path('', TabList.as_view(), name='tabs'),
    path('tab/<int:pk>/', TabDetail.as_view(), name='tab'),
    path('tab_create/', TabCreate.as_view(), name='tab_create'),
    path('tab_update/<int:pk>', TabUpdate.as_view(), name='tab_update'),
    path('tab_delete/<int:pk>', TabDelete.as_view(), name='tab_delete'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/tfe/models.py
from django.db import models
from django.contrib.auth.models import User


class Tab(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    band = models.CharField(max_length=100)
    album = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=100)
    instrument = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    tab_image = models.ImageField(upload_to='images/')
    audio_file = models.FileField()

    def __str__(self):
        return self.band + ' – ' + self.title

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/tfe/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy

from .models import Tab


# View for login functionality
class CustomLoginView(LoginView):
    # Specify the template
    template_name = 'tfe/login.html'
    # Specify needed fields for form
    fields = '__all__'
    # Redirect already authenticated user from that view
    redirect_authenticated_user = True

    # Redirect user if success
    def get_success_url(self):
        return reverse_lazy('tfe:tabs')


# View for register
class RegisterPageView(FormView):
    template_name = 'tfe/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tfe:tabs')

    # Save user
    def form_valid(self, form):
        user = form.save()

        if user is not None:
            login(self.request, user)
        return super(RegisterPageView, self).form_valid(form)

    # Redirect registered user
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tfe:tabs')
        return super(RegisterPageView, self).get(*args, **kwargs)


# View for tab list functionality
class TabList(ListView):
    model = Tab
    context_object_name = 'tabs'
    template_name = 'tfe/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        # Tabs count
        context['tab_count'] = context['tabs'].count()

        # User searching
        title_search_input = self.request.GET.get('search_area') or ''
        if title_search_input:
            context['tabs'] = context['tabs'].filter(
                # title__icontains=search_input,
                title__startswith=title_search_input,
            )

        context['title_search_input'] = title_search_input

        return context


class TabDetail(DetailView):
    model = Tab
    fields = '__all__'
    context_object_name = 'tab'


class TabCreate(LoginRequiredMixin, CreateView):
    model = Tab
    fields = ['band', 'album', 'title', 'instrument', 'description', 'tab_image', 'audio_file']
    success_url = reverse_lazy('tfe:tabs')


class TabUpdate(LoginRequiredMixin, UpdateView):
    model = Tab
    fields = '__all__'
    success_url = reverse_lazy('tfe:tabs')


class TabDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Tab
    context_object_name = 'tab'
    success_url = reverse_lazy('tfe:tabs')
    permission_required = 'tfe.can_delete_tabs'

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>Question: {{ question.question_text }}</h1>

<h2>Results:</h2>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/tfe/templates/tfe/index.html
{% extends 'tfe/main.html' %}
{% block content %}

    <div class="user-bar">
        {% if request.user.is_authenticated %}
            <p>YOU ARE LOGGED IN AS: {{ request.user }}</p>
            <a href="{% url 'tfe:logout' %}">LOGOUT</a>
        {% else %}
            <a href="{% url 'tfe:login' %}">LOGIN</a>
        {% endif %}
    </div>

    <h1 style="color: #e00000" class="tab-list-text">TAB LIST:</h1>
    {% if tab_count > 0 %}
        <h2>TFE has {{ tab_count }} tab{{ tab_count|pluralize:"s" }} submitted by users!</h2>
    {% else %}
        <h2>TFE has 0 tab{{ tab_count|pluralize:"s" }} submitted by users!</h2>
    {% endif %}

    <div class="search-create-wrapper">
        <form method="GET" class="search-area">
            <input type="text" name="search_area" value="{{ search_input }}">
            <input style="margin-left: 2%;" class="custom-button" type="submit" value="SEARCH">
        </form>
        <a class="custom-button" href="{% url 'tfe:tab_create' %}">CREATE PIECE OF ART</a>
    </div>

    <div class="tab-list-wrapper">
        {% for tab in tabs %}
            <div class="tab-wrapper">
                <div class="tab-band-title">
                    <p>{{ tab.band }} – {{ tab.title }}</p>
                    <a style="color: blue" href="{% url 'tfe:tab' tab.id %}">View</a>
                    <a style="color: green" href="{% url 'tfe:tab_update' tab.id %}">Edit</a>
                </div>
            </div>

            {% empty %}
                <h3>No tabs in list</h3>
        {% endfor %}
    </div>

    <!-- <table>
        <tr>
            <th>Tabs:</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        {% for tab in tabs %}
            <tr>
                <td>{{ tab.band }} – {{ tab.title }}</td>
                <td><a href="{% url 'tfe:tab' tab.id %}">View</a></td>
                <td><a href="{% url 'tfe:tab_update' tab.id %}">Edit</a></td>
                <td><a href="{% url 'tfe:tab_delete' tab.id %}">Delete</a></td>
            </tr>
            {% empty %}
                <h3>No tabs in list</h3>
        {% endfor %}
    </table> -->

{% endblock content %}

mysite/tfe/templates/tfe/login.html
{% extends 'tfe/main.html' %}
{% block content %}

<div class="user-bar">
	<h1>LOG IN TO TFE</h1>
</div>

<div class="tab-form">
	<form method="POST">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input style="margin-top: 4%;" class="custom-button" type="submit" value="Login">
	</form>
</div>

<p style="padding: 1%;">
	Don't have an account yet?
	<a style="text-decoration: underline;" href="{% url 'tfe:register' %}">
		Register
	</a>
</p>

{% endblock content %}

mysite/tfe/templates/tfe/main.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	
	<title>TFE</title>

	<!-- load fonts -->
	<link rel="preconnect" type="text/css" href="https://fonts.googleapis.com">
	<link rel="preconnect" type="text/css" href="https://fonts.gstatic.com" crossorigin>
	<link type="text/css" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

	<!-- load logo -->
	{% load static %}
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'tfe/images/bass_guitar_logo.png' %}">

	<!-- load styles -->
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'tfe/style.css' %}">
</head>
<body>
	<div class="wrapper">
		<div class="header-bar">
			<div>
				<a href="{% url 'tfe:tabs' %}">
					<img src="{% static 'tfe/images/bass_guitar_logo.png' %}" alt="logo" width="100px" height="100px">
				</a>
			</div>

			<h1 style="color: #0062ff;">TABS FOR EVERYONE</h1>
		</div>

		<div class="container">
			{% block content %}
				<!-- content goes here -->
			{% endblock content %}
		</div>

		<footer class="footer-bar">
			<div>
				<h1 style="color: #0062ff">IDB-19-07, Afanasyev V.A.</h1>
			</div>
		</footer>
	</div>
</body>
</html>

mysite/tfe/templates/tfe/register.html
{% extends 'tfe/main.html' %}
{% block content %}

<div class="user-bar">
	<h1>REGISTER</h1>
</div>

<div class="tab-form">
	<form method="POST">
		{% csrf_token %}
		<!--{{ form.as_p }}-->
		<label>{{ form.username.label }}</label>
		{{ form.username }}
		<label>{{ form.password1.label }}</label>
		{{ form.password1 }}
		<label>{{ form.password2.label }}</label>
		{{ form.password2 }}
		<br>
		<input style="margin-top: 4%;" class="custom-button" type="submit" value="REGISTER">
	</form>
</div>

<p style="margin-left: 1%; margin-top: 1%;">
	Already have an account?
	<a style="text-decoration: underline;" href="{% url 'tfe:login' %}">
			Login
	</a>
</p>

{% endblock content %}

mysite/tfe/templates/tfe/tab_confirm_delete.html
{% extends 'tfe/main.html' %}
{% block content %}

<a href="{% url 'tfe:tabs' %}">Nah, I'm out</a>
<form method="POST">
    {% csrf_token %}
    <p>Have you thought twice before deleting a piece of art? ["{{ tab }}"]</p>
    <input type="submit" value="I'm risky guy.">
</form>

{% endblock content %}

mysite/tfe/templates/tfe/tab_detail.html
{% extends 'tfe/main.html' %}
{% block content %}

{% load static %}
<img id="light-bulb" onclick="handleLightBulb()" 
	src="{% static 'tfe/images/light_bulb_off.jpg' %}"
	width="100px" height="200px">

<p style="font-weight: bold; color: white;">Specifically for Julia Sergeevna :)</p>

<script type="text/javascript">
	// Light bulb turning on/off
	function handleLightBulb() {
		let image = document.getElementById('light-bulb');
	  	if (image.src.match("on")) {
			image.src = "{% static 'tfe/images/light_bulb_off.jpg' %}";
	  	}
	  	else {
	  		image.src = "{% static 'tfe/images/light_bulb_on.jpg' %}";
	  	}
	}
</script>

<div class="user-bar">
	<a href="{% url 'tfe:tabs' %}"><p>&#8592; GO BACK</p></a>
</div>

<div class="tab-detail">
	<h1>Tab: {{ tab }}</h1>
	<img style="margin-top: 1%;" src="{{ tab.tab_image.url }}">
</div>

<audio controls>
    <source src="{{ tab.audio_file.url }}" type="audio/mpeg">
</audio>

<div class="tab-description">
	<h3>Description:</h3>
	{{ tab.description }}
</div>

{% endblock content %}

mysite/tfe/templates/tfe/tab_form.html
{% extends 'tfe/main.html' %}
{% block content %}

<div class="user-bar">
	<a href="{% url 'tfe:tabs' %}"><p>&#8592; GO BACK</p></a>
</div>

<div class="tab-form">
	<form method="POST" action="" enctype="multipart/form-data">
	    {% csrf_token %}
	    {{ form.as_p }}
    	<input style="margin-top: 2%;" class="custom-button" type="submit" value="SUBMIT TAB">
	</form>
</div>

{% endblock content %}